include_guard()

add_subdirectory(led)
add_subdirectory(button)
add_subdirectory(seven_seg_display)
add_subdirectory(dip_switch)
add_subdirectory(serial_terminal)
add_subdirectory(logic_analyzer)
add_subdirectory(ssd1306_oled)
add_subdirectory(gpio_server)
add_subdirectory(remote_uart)
add_subdirectory(remote_i2c_master)
add_subdirectory(remote_i2c_slave)
