name: windows

# Define the rules when this workflow should be applied
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Specify the type of the machine
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Configure the CMake project using the default generator (MSVC)
      - name: Configure CMake
        run: cmake -S . -B build/msvc

      # Build the project
      - name: Build
        run: cmake --build build/msvc --config Debug -j4

      # Run tests
      - name: Tests
        working-directory: build/msvc
        run: ctest --rerun-failed --output-on-failure --build-config Debug

# EOF
